version: "3"
services:
    web:
        container_name: web
        build: .
        ports:
            - "8000:8000"
        restart: on-failure
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
        volumes:
            - ./src:/src
        command:
            - /bin/sh
            - -c
            - |
                python3 manage.py migrate --skip-checks 
                python3 manage.py createadmin 
                python3 manage.py runserver 0.0.0.0:8000

    db:
        container_name: db
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'sports_accounting'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        volumes:
            - ./data/mysql/db:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            interval: 3s
            timeout: 5s
            retries: 5
        restart: always
