# Generated by Django 4.1.6 on 2023-03-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('balance_details_id', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.balancedetails'))),
                ('source', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
            ],
        ),
    ]
