# Generated by Django 4.1.6 on 2023-03-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
        ('cash_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_transaction',
            name='balance_details_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.balancedetails'),
        ),
    ]
