# Generated by Django 4.1.6 on 2023-03-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='LinkedTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member_module.member', verbose_name='Member')),
                ('transaction_bank_reference', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Linked Transaction',
                'verbose_name_plural': 'Linked Transactions',
                'db_table': 'LinkedTransaction',
            },
        ),
    ]
