# Generated by Django 4.1.6 on 2023-03-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedTransaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='member_module.member')),
                ('transaction_bank_reference', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.transaction')),
            ],
        ),
    ]
