# Generated by Django 4.1.6 on 2023-03-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedtransaction',
            options={'verbose_name': 'Linked Transaction', 'verbose_name_plural': 'Linked Transactions'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
