# Generated by Django 4.1.6 on 2023-03-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_balancedetails_currency_type_and_more'),
        ('member_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedtransaction',
            name='transaction_bank_reference',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.transaction'),
        ),
    ]
