# Generated by Django 4.1.6 on 2023-03-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('bank_reference', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('transaction_details', models.CharField(max_length=255)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.file')),
            ],
        ),
    ]
