# Generated by Django 4.1.6 on 2023-03-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancedetails',
            name='currency_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.currency'),
        ),
        migrations.AlterField(
            model_name='file',
            name='available_closing_balance_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_closing_balance_id', to='base_app.balancedetails'),
        ),
        migrations.AlterField(
            model_name='file',
            name='final_available_balance_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_available_balance_id', to='base_app.balancedetails'),
        ),
        migrations.AlterField(
            model_name='file',
            name='final_closing_balance_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_closing_balance_id', to='base_app.balancedetails'),
        ),
        migrations.AlterField(
            model_name='file',
            name='final_opening_balance_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_opening_balance_id', to='base_app.balancedetails'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_details_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='balance_details_id', to='base_app.balancedetails'),
        ),
    ]
